# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnum', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=128, unique=True)),
                ('itemname', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('notes', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
