# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-12 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_auto_20170711_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='itemid',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='itemid',
            field=models.ManyToManyField(related_name='products', to='salesapp.Product'),
        ),
    ]
