# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-12 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0005_auto_20170711_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='itemid',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='itemid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='salesapp.Product'),
            preserve_default=False,
        ),
    ]
